### ISSUE TITLE
Add mysql to github actions

### ISSUE THREAD

**Issue by darcys22** [darcys22/godbledger#117]
The next step in #49 is to run all the tests a second time using the mysql database rather than just a sqlite in memory database.

It appears possible and relatively straightforward to include mysql to a github action workflow. 

Found this blog post on the process:
https://freek.dev/1590-how-to-use-a-mysql-database-on-github-actions

Appears you add a 'service' to a github action job which in this case is mysql. Then you define the credentials and config. This repo appears to be an official github example page:
https://github.com/actions/virtual-environments

In particular this template for postgres looks helpful:
https://github.com/actions/example-services/blob/main/.github/workflows/postgres-service.yml

it appears we would do something like this:
```
...
  test:
    strategy:
      fail-fast: false # dont' want one scenario failing to deprive us of feedback on the others
      matrix:
        go-version: [1.14.x, 1.15.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    services:
        mysql:
            image: mysql:5.7
            env:
                MYSQL_ALLOW_EMPTY_PASSWORD: yes
                MYSQL_DATABASE: laravel_tags
            ports:
                - 3306
            options: --health-cmd="mysqladmin ping" --health-interval=10s
...
```

However just found this announcement:
https://github.blog/changelog/2020-02-21-github-actions-breaking-change-ubuntu-virtual-environments-will-no-longer-start-the-mysql-service-automatically/

Which may mean that it instead done via a step. Unsure how this would work with a windows container though
